version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    links:
      - app
volumes:
  reserved: